app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /

app_admin:
    resource: "@AppBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_confirmed:
    path: /
    defaults: { _controller: FOSUserBundle:Registration:confirmed }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
