# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  event_manager:
      class: AppBundle\Services\EventManager

  stripe_manager:
      class: AppBundle\Services\StripeManager
      autowire: true
      arguments: ['%stripe_secret_key%']

