imports:
    - { resource: parameters.yml }

services:

  event_manager:
      class: AppBundle\Services\EventManager

  stripe_manager:
      class: AppBundle\Services\StripeManager
      autowire: true
      arguments: ['%stripe_secret_key%']

  email_manager:
      class: AppBundle\Services\EmailManager
      arguments: ['@doctrine.orm.entity_manager', '@mailer', '@twig', '%admin_email%']

  club_service:
      class: AppBundle\Services\ClubService
      autowire: true

  dues_service:
      class: AppBundle\Services\DuesService
      autowire: true
